name: Build

on:
  push:
    branches: 
      - master
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: jorelali/setup-elm@v1
      with:
        elm-version: 0.19.1
    - run: elm make src/Main.elm --output=app.js
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: application
        path: app.js
